### ISSUE TITLE
Proper styling to the button

### ISSUE THREAD

**Issue by alkatrivedi** [alkatrivedi/Greeting-Card-Maker#7]
Give proper style to the view all card button
![Capture](https://user-images.githubusercontent.com/58396306/98839119-2bceb600-246b-11eb-94f9-4966ba28070a.PNG)

**Comment by shee35** [comment]
Added the following styling on buttons:

![Screenshot (171)](https://user-images.githubusercontent.com/58389098/99096809-bf83bc00-25fc-11eb-9654-dffff1db5905.png)
